//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicProcessingClass.WS_Affix {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.zizo.com.cn", ConfigurationName="WS_Affix.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: 命名空间 http://www.zizo.com.cn 的元素名称 targetCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zizo.com.cn/SaveFileToServer_V1", ReplyAction="*")]
        LogicProcessingClass.WS_Affix.SaveFileToServer_V1Response SaveFileToServer_V1(LogicProcessingClass.WS_Affix.SaveFileToServer_V1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveFileToServer_V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveFileToServer_V1", Namespace="http://www.zizo.com.cn", Order=0)]
        public LogicProcessingClass.WS_Affix.SaveFileToServer_V1RequestBody Body;
        
        public SaveFileToServer_V1Request() {
        }
        
        public SaveFileToServer_V1Request(LogicProcessingClass.WS_Affix.SaveFileToServer_V1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.zizo.com.cn")]
    public partial class SaveFileToServer_V1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int upploadPosition;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string targetCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] fileByte;
        
        public SaveFileToServer_V1RequestBody() {
        }
        
        public SaveFileToServer_V1RequestBody(int upploadPosition, string targetCode, string fileName, byte[] fileByte) {
            this.upploadPosition = upploadPosition;
            this.targetCode = targetCode;
            this.fileName = fileName;
            this.fileByte = fileByte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveFileToServer_V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveFileToServer_V1Response", Namespace="http://www.zizo.com.cn", Order=0)]
        public LogicProcessingClass.WS_Affix.SaveFileToServer_V1ResponseBody Body;
        
        public SaveFileToServer_V1Response() {
        }
        
        public SaveFileToServer_V1Response(LogicProcessingClass.WS_Affix.SaveFileToServer_V1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.zizo.com.cn")]
    public partial class SaveFileToServer_V1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveFileToServer_V1Result;
        
        public SaveFileToServer_V1ResponseBody() {
        }
        
        public SaveFileToServer_V1ResponseBody(string SaveFileToServer_V1Result) {
            this.SaveFileToServer_V1Result = SaveFileToServer_V1Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : LogicProcessingClass.WS_Affix.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<LogicProcessingClass.WS_Affix.ServiceSoap>, LogicProcessingClass.WS_Affix.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogicProcessingClass.WS_Affix.SaveFileToServer_V1Response LogicProcessingClass.WS_Affix.ServiceSoap.SaveFileToServer_V1(LogicProcessingClass.WS_Affix.SaveFileToServer_V1Request request) {
            return base.Channel.SaveFileToServer_V1(request);
        }
        
        public string SaveFileToServer_V1(int upploadPosition, string targetCode, string fileName, byte[] fileByte) {
            LogicProcessingClass.WS_Affix.SaveFileToServer_V1Request inValue = new LogicProcessingClass.WS_Affix.SaveFileToServer_V1Request();
            inValue.Body = new LogicProcessingClass.WS_Affix.SaveFileToServer_V1RequestBody();
            inValue.Body.upploadPosition = upploadPosition;
            inValue.Body.targetCode = targetCode;
            inValue.Body.fileName = fileName;
            inValue.Body.fileByte = fileByte;
            LogicProcessingClass.WS_Affix.SaveFileToServer_V1Response retVal = ((LogicProcessingClass.WS_Affix.ServiceSoap)(this)).SaveFileToServer_V1(inValue);
            return retVal.Body.SaveFileToServer_V1Result;
        }
    }
}
