//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicProcessingClass.WS_BS_CS_XML {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_BS_CS_XML.RptTransSoap")]
    public interface RptTransSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 XMLData 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadReport", ReplyAction="*")]
        LogicProcessingClass.WS_BS_CS_XML.UploadReportResponse UploadReport(LogicProcessingClass.WS_BS_CS_XML.UploadReportRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 XMLData 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadReportToCS", ReplyAction="*")]
        LogicProcessingClass.WS_BS_CS_XML.UploadReportToCSResponse UploadReportToCS(LogicProcessingClass.WS_BS_CS_XML.UploadReportToCSRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 XMLFileName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestUploadReport", ReplyAction="*")]
        LogicProcessingClass.WS_BS_CS_XML.TestUploadReportResponse TestUploadReport(LogicProcessingClass.WS_BS_CS_XML.TestUploadReportRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 XMLFileName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestUploadReportToCS", ReplyAction="*")]
        LogicProcessingClass.WS_BS_CS_XML.TestUploadReportToCSResponse TestUploadReportToCS(LogicProcessingClass.WS_BS_CS_XML.TestUploadReportToCSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadReport", Namespace="http://tempuri.org/", Order=0)]
        public LogicProcessingClass.WS_BS_CS_XML.UploadReportRequestBody Body;
        
        public UploadReportRequest() {
        }
        
        public UploadReportRequest(LogicProcessingClass.WS_BS_CS_XML.UploadReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] XMLData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SendUnit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ReceiveUnit;
        
        public UploadReportRequestBody() {
        }
        
        public UploadReportRequestBody(byte[] XMLData, string XMLFileName, string SendUnit, string ReceiveUnit) {
            this.XMLData = XMLData;
            this.XMLFileName = XMLFileName;
            this.SendUnit = SendUnit;
            this.ReceiveUnit = ReceiveUnit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public LogicProcessingClass.WS_BS_CS_XML.UploadReportResponseBody Body;
        
        public UploadReportResponse() {
        }
        
        public UploadReportResponse(LogicProcessingClass.WS_BS_CS_XML.UploadReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UploadReportResult;
        
        public UploadReportResponseBody() {
        }
        
        public UploadReportResponseBody(int UploadReportResult) {
            this.UploadReportResult = UploadReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadReportToCSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadReportToCS", Namespace="http://tempuri.org/", Order=0)]
        public LogicProcessingClass.WS_BS_CS_XML.UploadReportToCSRequestBody Body;
        
        public UploadReportToCSRequest() {
        }
        
        public UploadReportToCSRequest(LogicProcessingClass.WS_BS_CS_XML.UploadReportToCSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadReportToCSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] XMLData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SendUnit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ReceiveUnit;
        
        public UploadReportToCSRequestBody() {
        }
        
        public UploadReportToCSRequestBody(byte[] XMLData, string XMLFileName, string SendUnit, string ReceiveUnit) {
            this.XMLData = XMLData;
            this.XMLFileName = XMLFileName;
            this.SendUnit = SendUnit;
            this.ReceiveUnit = ReceiveUnit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadReportToCSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadReportToCSResponse", Namespace="http://tempuri.org/", Order=0)]
        public LogicProcessingClass.WS_BS_CS_XML.UploadReportToCSResponseBody Body;
        
        public UploadReportToCSResponse() {
        }
        
        public UploadReportToCSResponse(LogicProcessingClass.WS_BS_CS_XML.UploadReportToCSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadReportToCSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UploadReportToCSResult;
        
        public UploadReportToCSResponseBody() {
        }
        
        public UploadReportToCSResponseBody(int UploadReportToCSResult) {
            this.UploadReportToCSResult = UploadReportToCSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestUploadReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestUploadReport", Namespace="http://tempuri.org/", Order=0)]
        public LogicProcessingClass.WS_BS_CS_XML.TestUploadReportRequestBody Body;
        
        public TestUploadReportRequest() {
        }
        
        public TestUploadReportRequest(LogicProcessingClass.WS_BS_CS_XML.TestUploadReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestUploadReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XMLFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SendUnit;
        
        public TestUploadReportRequestBody() {
        }
        
        public TestUploadReportRequestBody(string XMLFileName, string SendUnit) {
            this.XMLFileName = XMLFileName;
            this.SendUnit = SendUnit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestUploadReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestUploadReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public LogicProcessingClass.WS_BS_CS_XML.TestUploadReportResponseBody Body;
        
        public TestUploadReportResponse() {
        }
        
        public TestUploadReportResponse(LogicProcessingClass.WS_BS_CS_XML.TestUploadReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestUploadReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestUploadReportResult;
        
        public TestUploadReportResponseBody() {
        }
        
        public TestUploadReportResponseBody(string TestUploadReportResult) {
            this.TestUploadReportResult = TestUploadReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestUploadReportToCSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestUploadReportToCS", Namespace="http://tempuri.org/", Order=0)]
        public LogicProcessingClass.WS_BS_CS_XML.TestUploadReportToCSRequestBody Body;
        
        public TestUploadReportToCSRequest() {
        }
        
        public TestUploadReportToCSRequest(LogicProcessingClass.WS_BS_CS_XML.TestUploadReportToCSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestUploadReportToCSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XMLFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SendUnit;
        
        public TestUploadReportToCSRequestBody() {
        }
        
        public TestUploadReportToCSRequestBody(string XMLFileName, string SendUnit) {
            this.XMLFileName = XMLFileName;
            this.SendUnit = SendUnit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestUploadReportToCSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestUploadReportToCSResponse", Namespace="http://tempuri.org/", Order=0)]
        public LogicProcessingClass.WS_BS_CS_XML.TestUploadReportToCSResponseBody Body;
        
        public TestUploadReportToCSResponse() {
        }
        
        public TestUploadReportToCSResponse(LogicProcessingClass.WS_BS_CS_XML.TestUploadReportToCSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestUploadReportToCSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestUploadReportToCSResult;
        
        public TestUploadReportToCSResponseBody() {
        }
        
        public TestUploadReportToCSResponseBody(string TestUploadReportToCSResult) {
            this.TestUploadReportToCSResult = TestUploadReportToCSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RptTransSoapChannel : LogicProcessingClass.WS_BS_CS_XML.RptTransSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RptTransSoapClient : System.ServiceModel.ClientBase<LogicProcessingClass.WS_BS_CS_XML.RptTransSoap>, LogicProcessingClass.WS_BS_CS_XML.RptTransSoap {
        
        public RptTransSoapClient() {
        }
        
        public RptTransSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RptTransSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RptTransSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RptTransSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogicProcessingClass.WS_BS_CS_XML.UploadReportResponse LogicProcessingClass.WS_BS_CS_XML.RptTransSoap.UploadReport(LogicProcessingClass.WS_BS_CS_XML.UploadReportRequest request) {
            return base.Channel.UploadReport(request);
        }
        
        public int UploadReport(byte[] XMLData, string XMLFileName, string SendUnit, string ReceiveUnit) {
            LogicProcessingClass.WS_BS_CS_XML.UploadReportRequest inValue = new LogicProcessingClass.WS_BS_CS_XML.UploadReportRequest();
            inValue.Body = new LogicProcessingClass.WS_BS_CS_XML.UploadReportRequestBody();
            inValue.Body.XMLData = XMLData;
            inValue.Body.XMLFileName = XMLFileName;
            inValue.Body.SendUnit = SendUnit;
            inValue.Body.ReceiveUnit = ReceiveUnit;
            LogicProcessingClass.WS_BS_CS_XML.UploadReportResponse retVal = ((LogicProcessingClass.WS_BS_CS_XML.RptTransSoap)(this)).UploadReport(inValue);
            return retVal.Body.UploadReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogicProcessingClass.WS_BS_CS_XML.UploadReportToCSResponse LogicProcessingClass.WS_BS_CS_XML.RptTransSoap.UploadReportToCS(LogicProcessingClass.WS_BS_CS_XML.UploadReportToCSRequest request) {
            return base.Channel.UploadReportToCS(request);
        }
        
        public int UploadReportToCS(byte[] XMLData, string XMLFileName, string SendUnit, string ReceiveUnit) {
            LogicProcessingClass.WS_BS_CS_XML.UploadReportToCSRequest inValue = new LogicProcessingClass.WS_BS_CS_XML.UploadReportToCSRequest();
            inValue.Body = new LogicProcessingClass.WS_BS_CS_XML.UploadReportToCSRequestBody();
            inValue.Body.XMLData = XMLData;
            inValue.Body.XMLFileName = XMLFileName;
            inValue.Body.SendUnit = SendUnit;
            inValue.Body.ReceiveUnit = ReceiveUnit;
            LogicProcessingClass.WS_BS_CS_XML.UploadReportToCSResponse retVal = ((LogicProcessingClass.WS_BS_CS_XML.RptTransSoap)(this)).UploadReportToCS(inValue);
            return retVal.Body.UploadReportToCSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogicProcessingClass.WS_BS_CS_XML.TestUploadReportResponse LogicProcessingClass.WS_BS_CS_XML.RptTransSoap.TestUploadReport(LogicProcessingClass.WS_BS_CS_XML.TestUploadReportRequest request) {
            return base.Channel.TestUploadReport(request);
        }
        
        public string TestUploadReport(string XMLFileName, string SendUnit) {
            LogicProcessingClass.WS_BS_CS_XML.TestUploadReportRequest inValue = new LogicProcessingClass.WS_BS_CS_XML.TestUploadReportRequest();
            inValue.Body = new LogicProcessingClass.WS_BS_CS_XML.TestUploadReportRequestBody();
            inValue.Body.XMLFileName = XMLFileName;
            inValue.Body.SendUnit = SendUnit;
            LogicProcessingClass.WS_BS_CS_XML.TestUploadReportResponse retVal = ((LogicProcessingClass.WS_BS_CS_XML.RptTransSoap)(this)).TestUploadReport(inValue);
            return retVal.Body.TestUploadReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogicProcessingClass.WS_BS_CS_XML.TestUploadReportToCSResponse LogicProcessingClass.WS_BS_CS_XML.RptTransSoap.TestUploadReportToCS(LogicProcessingClass.WS_BS_CS_XML.TestUploadReportToCSRequest request) {
            return base.Channel.TestUploadReportToCS(request);
        }
        
        public string TestUploadReportToCS(string XMLFileName, string SendUnit) {
            LogicProcessingClass.WS_BS_CS_XML.TestUploadReportToCSRequest inValue = new LogicProcessingClass.WS_BS_CS_XML.TestUploadReportToCSRequest();
            inValue.Body = new LogicProcessingClass.WS_BS_CS_XML.TestUploadReportToCSRequestBody();
            inValue.Body.XMLFileName = XMLFileName;
            inValue.Body.SendUnit = SendUnit;
            LogicProcessingClass.WS_BS_CS_XML.TestUploadReportToCSResponse retVal = ((LogicProcessingClass.WS_BS_CS_XML.RptTransSoap)(this)).TestUploadReportToCS(inValue);
            return retVal.Body.TestUploadReportToCSResult;
        }
    }
}
