//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZQFW.WS_XML {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_XML.wsRptTransSoap")]
    public interface wsRptTransSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 XMLData 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadReport", ReplyAction="*")]
        ZQFW.WS_XML.UploadReportResponse UploadReport(ZQFW.WS_XML.UploadReportRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UnitCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getReportList", ReplyAction="*")]
        ZQFW.WS_XML.getReportListResponse getReportList(ZQFW.WS_XML.getReportListRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UnitCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownLoadReport", ReplyAction="*")]
        ZQFW.WS_XML.DownLoadReportResponse DownLoadReport(ZQFW.WS_XML.DownLoadReportRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 XMLFileName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownReportConfirm", ReplyAction="*")]
        ZQFW.WS_XML.DownReportConfirmResponse DownReportConfirm(ZQFW.WS_XML.DownReportConfirmRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 AContent 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        ZQFW.WS_XML.SendMessageResponse SendMessage(ZQFW.WS_XML.SendMessageRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 AUnitCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMessage", ReplyAction="*")]
        ZQFW.WS_XML.getMessageResponse getMessage(ZQFW.WS_XML.getMessageRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 unitCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLimitTime", ReplyAction="*")]
        ZQFW.WS_XML.GetLimitTimeResponse GetLimitTime(ZQFW.WS_XML.GetLimitTimeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetProvinceUpperIPResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProvinceUpperIP", ReplyAction="*")]
        ZQFW.WS_XML.GetProvinceUpperIPResponse GetProvinceUpperIP(ZQFW.WS_XML.GetProvinceUpperIPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadReport", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.UploadReportRequestBody Body;
        
        public UploadReportRequest() {
        }
        
        public UploadReportRequest(ZQFW.WS_XML.UploadReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] XMLData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SendUnit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ReceiveUnit;
        
        public UploadReportRequestBody() {
        }
        
        public UploadReportRequestBody(byte[] XMLData, string XMLFileName, string SendUnit, string ReceiveUnit) {
            this.XMLData = XMLData;
            this.XMLFileName = XMLFileName;
            this.SendUnit = SendUnit;
            this.ReceiveUnit = ReceiveUnit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.UploadReportResponseBody Body;
        
        public UploadReportResponse() {
        }
        
        public UploadReportResponse(ZQFW.WS_XML.UploadReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UploadReportResult;
        
        public UploadReportResponseBody() {
        }
        
        public UploadReportResponseBody(int UploadReportResult) {
            this.UploadReportResult = UploadReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReportListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReportList", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.getReportListRequestBody Body;
        
        public getReportListRequest() {
        }
        
        public getReportListRequest(ZQFW.WS_XML.getReportListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getReportListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UnitCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ORDCode;
        
        public getReportListRequestBody() {
        }
        
        public getReportListRequestBody(string UnitCode, string ORDCode) {
            this.UnitCode = UnitCode;
            this.ORDCode = ORDCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReportListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReportListResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.getReportListResponseBody Body;
        
        public getReportListResponse() {
        }
        
        public getReportListResponse(ZQFW.WS_XML.getReportListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getReportListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getReportListResult;
        
        public getReportListResponseBody() {
        }
        
        public getReportListResponseBody(string getReportListResult) {
            this.getReportListResult = getReportListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoadReport", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.DownLoadReportRequestBody Body;
        
        public DownLoadReportRequest() {
        }
        
        public DownLoadReportRequest(ZQFW.WS_XML.DownLoadReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownLoadReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UnitCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLFileName;
        
        public DownLoadReportRequestBody() {
        }
        
        public DownLoadReportRequestBody(string UnitCode, string XMLFileName) {
            this.UnitCode = UnitCode;
            this.XMLFileName = XMLFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoadReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.DownLoadReportResponseBody Body;
        
        public DownLoadReportResponse() {
        }
        
        public DownLoadReportResponse(ZQFW.WS_XML.DownLoadReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownLoadReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownLoadReportResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FileSize;
        
        public DownLoadReportResponseBody() {
        }
        
        public DownLoadReportResponseBody(byte[] DownLoadReportResult, int FileSize) {
            this.DownLoadReportResult = DownLoadReportResult;
            this.FileSize = FileSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownReportConfirmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownReportConfirm", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.DownReportConfirmRequestBody Body;
        
        public DownReportConfirmRequest() {
        }
        
        public DownReportConfirmRequest(ZQFW.WS_XML.DownReportConfirmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownReportConfirmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XMLFileName;
        
        public DownReportConfirmRequestBody() {
        }
        
        public DownReportConfirmRequestBody(string XMLFileName) {
            this.XMLFileName = XMLFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownReportConfirmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownReportConfirmResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.DownReportConfirmResponseBody Body;
        
        public DownReportConfirmResponse() {
        }
        
        public DownReportConfirmResponse(ZQFW.WS_XML.DownReportConfirmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownReportConfirmResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReceiveTime;
        
        public DownReportConfirmResponseBody() {
        }
        
        public DownReportConfirmResponseBody(string ReceiveTime) {
            this.ReceiveTime = ReceiveTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(ZQFW.WS_XML.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AMsgType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ASender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AReceiver;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(int AMsgType, string AContent, string ASender, string AReceiver) {
            this.AMsgType = AMsgType;
            this.AContent = AContent;
            this.ASender = ASender;
            this.AReceiver = AReceiver;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(ZQFW.WS_XML.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendMessageResponseBody {
        
        public SendMessageResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessage", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.getMessageRequestBody Body;
        
        public getMessageRequest() {
        }
        
        public getMessageRequest(ZQFW.WS_XML.getMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AUnitCode;
        
        public getMessageRequestBody() {
        }
        
        public getMessageRequestBody(string AUnitCode) {
            this.AUnitCode = AUnitCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.getMessageResponseBody Body;
        
        public getMessageResponse() {
        }
        
        public getMessageResponse(ZQFW.WS_XML.getMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getMessageResult;
        
        public getMessageResponseBody() {
        }
        
        public getMessageResponseBody(string getMessageResult) {
            this.getMessageResult = getMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLimitTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLimitTime", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.GetLimitTimeRequestBody Body;
        
        public GetLimitTimeRequest() {
        }
        
        public GetLimitTimeRequest(ZQFW.WS_XML.GetLimitTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLimitTimeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string unitCode;
        
        public GetLimitTimeRequestBody() {
        }
        
        public GetLimitTimeRequestBody(string unitCode) {
            this.unitCode = unitCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLimitTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLimitTimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.GetLimitTimeResponseBody Body;
        
        public GetLimitTimeResponse() {
        }
        
        public GetLimitTimeResponse(ZQFW.WS_XML.GetLimitTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLimitTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLimitTimeResult;
        
        public GetLimitTimeResponseBody() {
        }
        
        public GetLimitTimeResponseBody(string GetLimitTimeResult) {
            this.GetLimitTimeResult = GetLimitTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProvinceUpperIPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProvinceUpperIP", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.GetProvinceUpperIPRequestBody Body;
        
        public GetProvinceUpperIPRequest() {
        }
        
        public GetProvinceUpperIPRequest(ZQFW.WS_XML.GetProvinceUpperIPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProvinceUpperIPRequestBody {
        
        public GetProvinceUpperIPRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProvinceUpperIPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProvinceUpperIPResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZQFW.WS_XML.GetProvinceUpperIPResponseBody Body;
        
        public GetProvinceUpperIPResponse() {
        }
        
        public GetProvinceUpperIPResponse(ZQFW.WS_XML.GetProvinceUpperIPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProvinceUpperIPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProvinceUpperIPResult;
        
        public GetProvinceUpperIPResponseBody() {
        }
        
        public GetProvinceUpperIPResponseBody(string GetProvinceUpperIPResult) {
            this.GetProvinceUpperIPResult = GetProvinceUpperIPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsRptTransSoapChannel : ZQFW.WS_XML.wsRptTransSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsRptTransSoapClient : System.ServiceModel.ClientBase<ZQFW.WS_XML.wsRptTransSoap>, ZQFW.WS_XML.wsRptTransSoap {
        
        public wsRptTransSoapClient() {
        }
        
        public wsRptTransSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsRptTransSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsRptTransSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsRptTransSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZQFW.WS_XML.UploadReportResponse ZQFW.WS_XML.wsRptTransSoap.UploadReport(ZQFW.WS_XML.UploadReportRequest request) {
            return base.Channel.UploadReport(request);
        }
        
        public int UploadReport(byte[] XMLData, string XMLFileName, string SendUnit, string ReceiveUnit) {
            ZQFW.WS_XML.UploadReportRequest inValue = new ZQFW.WS_XML.UploadReportRequest();
            inValue.Body = new ZQFW.WS_XML.UploadReportRequestBody();
            inValue.Body.XMLData = XMLData;
            inValue.Body.XMLFileName = XMLFileName;
            inValue.Body.SendUnit = SendUnit;
            inValue.Body.ReceiveUnit = ReceiveUnit;
            ZQFW.WS_XML.UploadReportResponse retVal = ((ZQFW.WS_XML.wsRptTransSoap)(this)).UploadReport(inValue);
            return retVal.Body.UploadReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZQFW.WS_XML.getReportListResponse ZQFW.WS_XML.wsRptTransSoap.getReportList(ZQFW.WS_XML.getReportListRequest request) {
            return base.Channel.getReportList(request);
        }
        
        public string getReportList(string UnitCode, string ORDCode) {
            ZQFW.WS_XML.getReportListRequest inValue = new ZQFW.WS_XML.getReportListRequest();
            inValue.Body = new ZQFW.WS_XML.getReportListRequestBody();
            inValue.Body.UnitCode = UnitCode;
            inValue.Body.ORDCode = ORDCode;
            ZQFW.WS_XML.getReportListResponse retVal = ((ZQFW.WS_XML.wsRptTransSoap)(this)).getReportList(inValue);
            return retVal.Body.getReportListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZQFW.WS_XML.DownLoadReportResponse ZQFW.WS_XML.wsRptTransSoap.DownLoadReport(ZQFW.WS_XML.DownLoadReportRequest request) {
            return base.Channel.DownLoadReport(request);
        }
        
        public byte[] DownLoadReport(string UnitCode, string XMLFileName, out int FileSize) {
            ZQFW.WS_XML.DownLoadReportRequest inValue = new ZQFW.WS_XML.DownLoadReportRequest();
            inValue.Body = new ZQFW.WS_XML.DownLoadReportRequestBody();
            inValue.Body.UnitCode = UnitCode;
            inValue.Body.XMLFileName = XMLFileName;
            ZQFW.WS_XML.DownLoadReportResponse retVal = ((ZQFW.WS_XML.wsRptTransSoap)(this)).DownLoadReport(inValue);
            FileSize = retVal.Body.FileSize;
            return retVal.Body.DownLoadReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZQFW.WS_XML.DownReportConfirmResponse ZQFW.WS_XML.wsRptTransSoap.DownReportConfirm(ZQFW.WS_XML.DownReportConfirmRequest request) {
            return base.Channel.DownReportConfirm(request);
        }
        
        public string DownReportConfirm(string XMLFileName) {
            ZQFW.WS_XML.DownReportConfirmRequest inValue = new ZQFW.WS_XML.DownReportConfirmRequest();
            inValue.Body = new ZQFW.WS_XML.DownReportConfirmRequestBody();
            inValue.Body.XMLFileName = XMLFileName;
            ZQFW.WS_XML.DownReportConfirmResponse retVal = ((ZQFW.WS_XML.wsRptTransSoap)(this)).DownReportConfirm(inValue);
            return retVal.Body.ReceiveTime;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZQFW.WS_XML.SendMessageResponse ZQFW.WS_XML.wsRptTransSoap.SendMessage(ZQFW.WS_XML.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public void SendMessage(int AMsgType, string AContent, string ASender, string AReceiver) {
            ZQFW.WS_XML.SendMessageRequest inValue = new ZQFW.WS_XML.SendMessageRequest();
            inValue.Body = new ZQFW.WS_XML.SendMessageRequestBody();
            inValue.Body.AMsgType = AMsgType;
            inValue.Body.AContent = AContent;
            inValue.Body.ASender = ASender;
            inValue.Body.AReceiver = AReceiver;
            ZQFW.WS_XML.SendMessageResponse retVal = ((ZQFW.WS_XML.wsRptTransSoap)(this)).SendMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZQFW.WS_XML.getMessageResponse ZQFW.WS_XML.wsRptTransSoap.getMessage(ZQFW.WS_XML.getMessageRequest request) {
            return base.Channel.getMessage(request);
        }
        
        public string getMessage(string AUnitCode) {
            ZQFW.WS_XML.getMessageRequest inValue = new ZQFW.WS_XML.getMessageRequest();
            inValue.Body = new ZQFW.WS_XML.getMessageRequestBody();
            inValue.Body.AUnitCode = AUnitCode;
            ZQFW.WS_XML.getMessageResponse retVal = ((ZQFW.WS_XML.wsRptTransSoap)(this)).getMessage(inValue);
            return retVal.Body.getMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZQFW.WS_XML.GetLimitTimeResponse ZQFW.WS_XML.wsRptTransSoap.GetLimitTime(ZQFW.WS_XML.GetLimitTimeRequest request) {
            return base.Channel.GetLimitTime(request);
        }
        
        public string GetLimitTime(string unitCode) {
            ZQFW.WS_XML.GetLimitTimeRequest inValue = new ZQFW.WS_XML.GetLimitTimeRequest();
            inValue.Body = new ZQFW.WS_XML.GetLimitTimeRequestBody();
            inValue.Body.unitCode = unitCode;
            ZQFW.WS_XML.GetLimitTimeResponse retVal = ((ZQFW.WS_XML.wsRptTransSoap)(this)).GetLimitTime(inValue);
            return retVal.Body.GetLimitTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZQFW.WS_XML.GetProvinceUpperIPResponse ZQFW.WS_XML.wsRptTransSoap.GetProvinceUpperIP(ZQFW.WS_XML.GetProvinceUpperIPRequest request) {
            return base.Channel.GetProvinceUpperIP(request);
        }
        
        public string GetProvinceUpperIP() {
            ZQFW.WS_XML.GetProvinceUpperIPRequest inValue = new ZQFW.WS_XML.GetProvinceUpperIPRequest();
            inValue.Body = new ZQFW.WS_XML.GetProvinceUpperIPRequestBody();
            ZQFW.WS_XML.GetProvinceUpperIPResponse retVal = ((ZQFW.WS_XML.wsRptTransSoap)(this)).GetProvinceUpperIP(inValue);
            return retVal.Body.GetProvinceUpperIPResult;
        }
    }
}
